#!/bin/sh

# Load and unload hello module

module="hello"

case "$1" in
	start)
		echo "Loading hello module"
		insmod /lib/modules/${module}.ko
		;;

	stop)
		echo "Unloading hello module"
		rmmod  ${module}
		;;

	*)
		echo "Usage: $0 {start|stop}"
esac

exit 0


